### ISSUE TITLE
pip install green-bit-llm  , faill - "requirements.txt"  No such file 

### ISSUE THREAD

**Issue by lyon-bit** [GreenBitAI/green-bit-llm#15]
pip install green-bit-llm
Collecting green-bit-llm
  Using cached green_bit_llm-0.2.3.tar.gz (54 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6s7bxw0s/green-bit-llm_d7da7a280ba041c2b651b8f9d0e494c0/setup.py", line 7, in <module>
          with open(Path(__file__).parent / "requirements.txt") as fid:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-6s7bxw0s/green-bit-llm_d7da7a280ba041c2b651b8f9d0e494c0/requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Jopyth** [comment]
Thank you for reporting the issue, unfortunately our source distribution is still incorrect. We are going to fix it soon, in the meantime, you can try to use version 0.2.0 (which has a binary release):

`pip install green-bit-llm=0.2.0`
