### ISSUE TITLE
About the NAS method

### ISSUE THREAD

**Issue by hanhanpp** [GreenBitAI/green-bit-llm#18]
Hi,
Does the NAS -based  quantization method released?  I want to learn how to quant a model by the proposed NAS method.

**Comment by yanghaojin** [comment]
Thanks for your interests!

As this technology is still under further improvement, we are not yet fully ready to release our quantization pipeline. However, we will upgrade the LLAMA3 and Qwen2 models soon, and the accuracy of the quantization models will be significantly improved. Please stay tuned.

BR HJ
